version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    command: python /usr/src/app/webapp/app.py
    volumes:
      - ./webapp:/usr/src/app/webapp
      - audio-storage:/path/to/save  # Map a volume for audio file storage
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: mydatabase


volumes:
  postgres-data:
  audio-storage:  # Define the volume for audio storage
